disabled_rules:
  - identifier_name
  - type_name
  - function_parameter_count

excluded:
  - Pods

line_length:
  warning: 122
  ignores_comments: true
  ignores_function_declarations: true

function_body_length:
  warning: 42
