disabled_rules:
  - type_name

excluded:
  - Pods

line_length:
  warning: 130
  error: 180
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 42
# enables the usage of variable 'id'
identifier_name:
  excluded: # excluded via string array
    - id
    - a
    - r
    - g
    - b
